// <auto-generated />

namespace DevZest.Data.Wpf.Resources
{
	using System;
    using System.CodeDom.Compiler;
    using System.Globalization;
    using System.Resources;
    using System.Reflection;
    using System.Threading;

    // <summary>
    // Strongly-typed and parameterized string resources.
    // </summary>
    [GeneratedCode("Resources.tt", "1.0.0.0")]
    internal static class Strings
    {
        // <summary>
        // A string like "The GridRange does not belong to the same DataSetControl."
        // </summary>
        internal static string GridRange_InvalidDataSetControl
        {
            get { return ResourceLoader.GetString(ResourceLoader.GridRange_InvalidDataSetControl); }
        }

        // <summary>
        // A string like "Invalid GridItem for this GridTemplate. Verification failed for GridItem.Owner or GirdItem.ParentModel property."
        // </summary>
        internal static string GridTemplate_InvalidGridItem
        {
            get { return ResourceLoader.GetString(ResourceLoader.GridTemplate_InvalidGridItem); }
        }

        // <summary>
        // A string like "The GridTemplate is currently sealed (read-only)."
        // </summary>
        internal static string GridTemplate_VerifyIsSealed
        {
            get { return ResourceLoader.GetString(ResourceLoader.GridTemplate_VerifyIsSealed); }
        }
    }

    // <summary>
    // Strongly-typed and parameterized exception factory.
    // </summary>
    [GeneratedCode("Resources.tt", "1.0.0.0")]
    internal static class Error
    {
        // <summary>
        // InvalidOperationException with message like "The GridTemplate is currently sealed (read-only)."
        // </summary>
        internal static Exception GridTemplate_VerifyIsSealed()
        {
            return new InvalidOperationException(Strings.GridTemplate_VerifyIsSealed);
        }

        // <summary>
        // The exception that is thrown when the value of an argument is outside the allowable range of values as defined by the invoked method.
        // </summary>
        internal static Exception Argument(string message, string paramName)
        {
            return new ArgumentException(message, paramName);
        }

        // <summary>
        // The exception that is thrown when the value of an argument is outside the allowable range of values as defined by the invoked method.
        // </summary>
        internal static Exception ArgumentOutOfRange(string paramName)
        {
            return new ArgumentOutOfRangeException(paramName);
        }
    }

    // <summary>
    // AutoGenerated resource class. Usage:
    // string s = ResourceLoader.GetString(ResourceLoader.MyIdenfitier);
    // </summary>
    [GeneratedCode("Resources.tt", "1.0.0.0")]
    internal sealed class ResourceLoader
    {
        internal const string GridRange_InvalidDataSetControl = "GridRange_InvalidDataSetControl";
        internal const string GridTemplate_InvalidGridItem = "GridTemplate_InvalidGridItem";
        internal const string GridTemplate_VerifyIsSealed = "GridTemplate_VerifyIsSealed";

        private static ResourceLoader loader;
        private readonly ResourceManager resources;

        private ResourceLoader()
        {
            resources = new ResourceManager("DevZest.Data.Wpf.Properties.Resources", typeof(ResourceLoader).GetTypeInfo().Assembly);
        }

        private static ResourceLoader GetLoader()
        {
            if (loader == null)
            {
                var sr = new ResourceLoader();
                Interlocked.CompareExchange(ref loader, sr, null);
            }
            return loader;
        }

        private static CultureInfo Culture
        {
            get { return null /*use ResourceManager default, CultureInfo.CurrentUICulture*/; }
        }

        public static ResourceManager Resources
        {
            get { return GetLoader().resources; }
        }

        public static string GetString(string name, params object[] args)
        {
            var sys = GetLoader();
            if (sys == null)
            {
                return null;
            }

            var res = sys.resources.GetString(name, Culture);

            if (args != null
                && args.Length > 0)
            {
                for (var i = 0; i < args.Length; i ++)
                {
                    var value = args[i] as String;
                    if (value != null
                        && value.Length > 1024)
                    {
                        args[i] = value.Substring(0, 1024 - 3) + "...";
                    }
                }
                return String.Format(CultureInfo.CurrentCulture, res, args);
            }
            else
            {
                return res;
            }
        }

        public static string GetString(string name)
        {
            var sys = GetLoader();
            if (sys == null)
            {
                return null;
            }
            return sys.resources.GetString(name, Culture);
        }
    }
}
