// <auto-generated />

namespace DevZest.Data.SqlServer.Resources
{
	using System;
    using System.CodeDom.Compiler;
    using System.Globalization;
    using System.Resources;
    using System.Reflection;
    using System.Threading;

    // <summary>
    // Strongly-typed and parameterized string resources.
    // </summary>
    [GeneratedCode("Resources.tt", "1.0.0.0")]
    internal static class Strings
    {
        // <summary>
        // A string like "The column type {0} is not supported."
        // </summary>
        internal static string ColumnTypeNotSupported(object p0)
        {
            return ResourceLoader.GetString(ResourceLoader.ColumnTypeNotSupported, p0);
        }

        // <summary>
        // A string like "The constraint type {0} is not supported."
        // </summary>
        internal static string ConstraintTypeNotSupported(object p0)
        {
            return ResourceLoader.GetString(ResourceLoader.ConstraintTypeNotSupported, p0);
        }

        // <summary>
        // A string like "The function {0} is not supported."
        // </summary>
        internal static string FunctionNotSupported(object p0)
        {
            return ResourceLoader.GetString(ResourceLoader.FunctionNotSupported, p0);
        }

        // <summary>
        // A string like "The table name '{0}' is not valid."
        // </summary>
        internal static string InvalidTableName(object p0)
        {
            return ResourceLoader.GetString(ResourceLoader.InvalidTableName, p0);
        }

        // <summary>
        // A string like "The SqlDbType {0} is not supported on SQL Server Version {1}."
        // </summary>
        internal static string SqlDbTypeNotSupported(object p0, object p1)
        {
            return ResourceLoader.GetString(ResourceLoader.SqlDbTypeNotSupported, p0, p1);
        }

        // <summary>
        // A string like "The SQL Server version {0} is not supported."
        // </summary>
        internal static string SqlVersionNotSupported(object p0)
        {
            return ResourceLoader.GetString(ResourceLoader.SqlVersionNotSupported, p0);
        }
    }

    // <summary>
    // Strongly-typed and parameterized exception factory.
    // </summary>
    [GeneratedCode("Resources.tt", "1.0.0.0")]
    internal static class Error
    {
        // <summary>
        // NotSupportedException with message like "The column type {0} is not supported."
        // </summary>
        internal static Exception ColumnTypeNotSupported(object p0)
        {
            return new NotSupportedException(Strings.ColumnTypeNotSupported(p0));
        }

        // <summary>
        // NotSupportedException with message like "The constraint type {0} is not supported."
        // </summary>
        internal static Exception ConstraintTypeNotSupported(object p0)
        {
            return new NotSupportedException(Strings.ConstraintTypeNotSupported(p0));
        }

        // <summary>
        // NotSupportedException with message like "The function {0} is not supported."
        // </summary>
        internal static Exception FunctionNotSupported(object p0)
        {
            return new NotSupportedException(Strings.FunctionNotSupported(p0));
        }

        // <summary>
        // FormatException with message like "The table name '{0}' is not valid."
        // </summary>
        internal static Exception InvalidTableName(object p0)
        {
            return new FormatException(Strings.InvalidTableName(p0));
        }

        // <summary>
        // NotSupportedException with message like "The SqlDbType {0} is not supported on SQL Server Version {1}."
        // </summary>
        internal static Exception SqlDbTypeNotSupported(object p0, object p1)
        {
            return new NotSupportedException(Strings.SqlDbTypeNotSupported(p0, p1));
        }

        // <summary>
        // NotSupportedException with message like "The SQL Server version {0} is not supported."
        // </summary>
        internal static Exception SqlVersionNotSupported(object p0)
        {
            return new NotSupportedException(Strings.SqlVersionNotSupported(p0));
        }

        // <summary>
        // The exception that is thrown when the value of an argument is outside the allowable range of values as defined by the invoked method.
        // </summary>
        internal static Exception Argument(string message, string paramName)
        {
            return new ArgumentException(message, paramName);
        }

        // <summary>
        // The exception that is thrown when the value of an argument is outside the allowable range of values as defined by the invoked method.
        // </summary>
        internal static Exception ArgumentOutOfRange(string paramName)
        {
            return new ArgumentOutOfRangeException(paramName);
        }
    }

    // <summary>
    // AutoGenerated resource class. Usage:
    // string s = ResourceLoader.GetString(ResourceLoader.MyIdenfitier);
    // </summary>
    [GeneratedCode("Resources.tt", "1.0.0.0")]
    internal sealed class ResourceLoader
    {
        internal const string ColumnTypeNotSupported = "ColumnTypeNotSupported";
        internal const string ConstraintTypeNotSupported = "ConstraintTypeNotSupported";
        internal const string FunctionNotSupported = "FunctionNotSupported";
        internal const string InvalidTableName = "InvalidTableName";
        internal const string SqlDbTypeNotSupported = "SqlDbTypeNotSupported";
        internal const string SqlVersionNotSupported = "SqlVersionNotSupported";

        private static ResourceLoader loader;
        private readonly ResourceManager resources;

        private ResourceLoader()
        {
            resources = new ResourceManager("DevZest.Data.SqlServer.Properties.Resources", typeof(ResourceLoader).GetTypeInfo().Assembly);
        }

        private static ResourceLoader GetLoader()
        {
            if (loader == null)
            {
                var sr = new ResourceLoader();
                Interlocked.CompareExchange(ref loader, sr, null);
            }
            return loader;
        }

        private static CultureInfo Culture
        {
            get { return null /*use ResourceManager default, CultureInfo.CurrentUICulture*/; }
        }

        public static ResourceManager Resources
        {
            get { return GetLoader().resources; }
        }

        public static string GetString(string name, params object[] args)
        {
            var sys = GetLoader();
            if (sys == null)
            {
                return null;
            }

            var res = sys.resources.GetString(name, Culture);

            if (args != null
                && args.Length > 0)
            {
                for (var i = 0; i < args.Length; i ++)
                {
                    var value = args[i] as String;
                    if (value != null
                        && value.Length > 1024)
                    {
                        args[i] = value.Substring(0, 1024 - 3) + "...";
                    }
                }
                return String.Format(CultureInfo.CurrentCulture, res, args);
            }
            else
            {
                return res;
            }
        }

        public static string GetString(string name)
        {
            var sys = GetLoader();
            if (sys == null)
            {
                return null;
            }
            return sys.resources.GetString(name, Culture);
        }
    }
}
