'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class UserMessages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DevZest.Samples.AdventureWorksLT.UserMessages", GetType(UserMessages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ListPrice cannot be negative value..
        '''</summary>
        Friend Shared ReadOnly Property CK_Product_ListPrice() As String
            Get
                Return ResourceManager.GetString("CK_Product_ListPrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SellEndDate cannot be earlier than SellStartDate..
        '''</summary>
        Friend Shared ReadOnly Property CK_Product_SellEndDate() As String
            Get
                Return ResourceManager.GetString("CK_Product_SellEndDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to StandardCost cannot be negative value..
        '''</summary>
        Friend Shared ReadOnly Property CK_Product_StandardCost() As String
            Get
                Return ResourceManager.GetString("CK_Product_StandardCost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weight cannot be negative value..
        '''</summary>
        Friend Shared ReadOnly Property CK_Product_Weight() As String
            Get
                Return ResourceManager.GetString("CK_Product_Weight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OrderQty must be greater than zero..
        '''</summary>
        Friend Shared ReadOnly Property CK_SalesOrderDetail_OrderQty() As String
            Get
                Return ResourceManager.GetString("CK_SalesOrderDetail_OrderQty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UnitPrice cannot be negative..
        '''</summary>
        Friend Shared ReadOnly Property CK_SalesOrderDetail_UnitPrice() As String
            Get
                Return ResourceManager.GetString("CK_SalesOrderDetail_UnitPrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UnitPriceDiscount cannot be negative..
        '''</summary>
        Friend Shared ReadOnly Property CK_SalesOrderDetail_UnitPriceDiscount() As String
            Get
                Return ResourceManager.GetString("CK_SalesOrderDetail_UnitPriceDiscount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DueDate cannot be earlier than OrderDate..
        '''</summary>
        Friend Shared ReadOnly Property CK_SalesOrderHeader_DueDate() As String
            Get
                Return ResourceManager.GetString("CK_SalesOrderHeader_DueDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Freight cannot be a negtive value..
        '''</summary>
        Friend Shared ReadOnly Property CK_SalesOrderHeader_Freight() As String
            Get
                Return ResourceManager.GetString("CK_SalesOrderHeader_Freight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ShipDate cannot be earlier than OrderDate..
        '''</summary>
        Friend Shared ReadOnly Property CK_SalesOrderHeader_ShipDate() As String
            Get
                Return ResourceManager.GetString("CK_SalesOrderHeader_ShipDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Status value..
        '''</summary>
        Friend Shared ReadOnly Property CK_SalesOrderHeader_Status() As String
            Get
                Return ResourceManager.GetString("CK_SalesOrderHeader_Status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SubTotal cannot be a negative value..
        '''</summary>
        Friend Shared ReadOnly Property CK_SalesOrderHeader_SubTotal() As String
            Get
                Return ResourceManager.GetString("CK_SalesOrderHeader_SubTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TaxAmt cannot be a negtive value..
        '''</summary>
        Friend Shared ReadOnly Property CK_SalesOrderHeader_TaxAmt() As String
            Get
                Return ResourceManager.GetString("CK_SalesOrderHeader_TaxAmt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sales order must have detail line(s)..
        '''</summary>
        Friend Shared ReadOnly Property Validation_SalesOrder_LineCount() As String
            Get
                Return ResourceManager.GetString("Validation_SalesOrder_LineCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value is required for field &apos;{0}&apos;..
        '''</summary>
        Friend Shared ReadOnly Property Validation_ValueIsRequired() As String
            Get
                Return ResourceManager.GetString("Validation_ValueIsRequired", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
