'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My

    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Strings

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
            MyBase.New
        End Sub

        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DevZest.Samples.AdventureWorksLT.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = Value
            End Set
        End Property

        '''<summary>
        '''  Looks up a localized string similar to [
        '''   {
        '''      &quot;ProductCategoryID&quot; : 1,
        '''      &quot;ParentProductCategoryID&quot; : null,
        '''      &quot;Name&quot; : &quot;Bikes&quot;,
        '''      &quot;RowGuid&quot; : &quot;cfbda25c-df71-47a7-b81b-64ee161aa37c&quot;,
        '''      &quot;ModifiedDate&quot; : &quot;2002-06-01T00:00:00.000&quot;,
        '''      &quot;SubCategories&quot; : []
        '''   },
        '''   {
        '''      &quot;ProductCategoryID&quot; : 2,
        '''      &quot;ParentProductCategoryID&quot; : null,
        '''      &quot;Name&quot; : &quot;Other&quot;,
        '''      &quot;RowGuid&quot; : &quot;09e91437-ba4f-4b1a-8215-74184fd95db8&quot;,
        '''      &quot;ModifiedDate&quot; : &quot;2002-06-01T00:00:00.000&quot;,
        '''      &quot;SubCategories&quot; : []
        '''   },
        '''   {
        '''      [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Mock_ProductCategory() As String
            Get
                Return ResourceManager.GetString("Mock_ProductCategory", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to [
        '''   {
        '''      &quot;SalesOrderID&quot; : 1,
        '''      &quot;SalesOrderDetailID&quot; : 1,
        '''      &quot;OrderQty&quot; : 1,
        '''      &quot;ProductID&quot; : 836,
        '''      &quot;UnitPrice&quot; : 356.8980,
        '''      &quot;UnitPriceDiscount&quot; : 0.0000,
        '''      &quot;LineTotal&quot; : 356.8980,
        '''      &quot;RowGuid&quot; : &quot;e3a1994c-7a68-4ce8-96a3-77fdd3bbd730&quot;,
        '''      &quot;ModifiedDate&quot; : &quot;2008-06-01T00:00:00.000&quot;
        '''   },
        '''   {
        '''      &quot;SalesOrderID&quot; : 1,
        '''      &quot;SalesOrderDetailID&quot; : 2,
        '''      &quot;OrderQty&quot; : 1,
        '''      &quot;ProductID&quot; : 822,
        '''      &quot;UnitPrice&quot; : 356.8980,
        '''      &quot;UnitPriceDiscount&quot; : 0.000 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Mock_SalesOrderDetail() As String
            Get
                Return ResourceManager.GetString("Mock_SalesOrderDetail", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to [
        '''   {
        '''      &quot;SalesOrderID&quot; : 1,
        '''      &quot;RevisionNumber&quot; : 2,
        '''      &quot;OrderDate&quot; : &quot;2008-06-01T00:00:00.000&quot;,
        '''      &quot;DueDate&quot; : &quot;2008-06-13T00:00:00.000&quot;,
        '''      &quot;ShipDate&quot; : &quot;2008-06-08T00:00:00.000&quot;,
        '''      &quot;Status&quot; : 5,
        '''      &quot;OnlineOrderFlag&quot; : false,
        '''      &quot;SalesOrderNumber&quot; : &quot;SO71774&quot;,
        '''      &quot;PurchaseOrderNumber&quot; : &quot;PO348186287&quot;,
        '''      &quot;AccountNumber&quot; : &quot;10-4020-000609&quot;,
        '''      &quot;CustomerID&quot; : 29847,
        '''      &quot;ShipToAddressID&quot; : 1092,
        '''      &quot;BillToAddressID&quot; : 1092,
        '''      &quot;ShipMethod&quot; : &quot;CARGO  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Mock_SalesOrderHeader() As String
            Get
                Return ResourceManager.GetString("Mock_SalesOrderHeader", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
