// <auto-generated />
namespace DevZest.Data
{
    using System.Diagnostics;
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class UIText
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("DevZest.Data.UIText", typeof(UIText).GetTypeInfo().Assembly);

        /// <summary>
        /// _Sort...
        /// </summary>
        public static string ColumnHeader_SortEditCommandText
        {
            get { return GetString("ColumnHeader_SortEditCommandText"); }
        }

        /// <summary>
        /// Column
        /// </summary>
        public static string SortDescription_Column
        {
            get { return GetString("SortDescription_Column"); }
        }

        /// <summary>
        /// Direction
        /// </summary>
        public static string SortDescription_Direction
        {
            get { return GetString("SortDescription_Direction"); }
        }

        /// <summary>
        /// {input} is required.
        /// </summary>
        public static string SortDescription_InputRequired(object input)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("SortDescription_InputRequired", "input"), input);
        }

        /// <summary>
        /// Sort
        /// </summary>
        public static string SortEditorWindow_Title
        {
            get { return GetString("SortEditorWindow_Title"); }
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
