// <auto-generated />
namespace DevZest.Data
{
    using System.Diagnostics;
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class UIText
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("DevZest.Data.UIText", typeof(UIText).GetTypeInfo().Assembly);

        /// <summary>
        /// _Sort...
        /// </summary>
        public static string ColumnHeader_SortEditCommandText
        {
            get { return GetString("ColumnHeader_SortEditCommandText"); }
        }

        /// <summary>
        /// Cancel
        /// </summary>
        public static string DataView_DataLoadCancelCommandText
        {
            get { return GetString("DataView_DataLoadCancelCommandText"); }
        }

        /// <summary>
        /// The operation has been cancelled.
        /// </summary>
        public static string DataView_DataLoadCancelled
        {
            get { return GetString("DataView_DataLoadCancelled"); }
        }

        /// <summary>
        /// Cancelling...
        /// </summary>
        public static string DataView_DataLoadCancelling
        {
            get { return GetString("DataView_DataLoadCancelling"); }
        }

        /// <summary>
        /// We're sorry, an error occured while loading data.
        /// </summary>
        public static string DataView_DataLoadFailed
        {
            get { return GetString("DataView_DataLoadFailed"); }
        }

        /// <summary>
        /// Retry
        /// </summary>
        public static string DataView_DataLoadRetryCommandText
        {
            get { return GetString("DataView_DataLoadRetryCommandText"); }
        }

        /// <summary>
        /// Column
        /// </summary>
        public static string SortDescription_Column
        {
            get { return GetString("SortDescription_Column"); }
        }

        /// <summary>
        /// Direction
        /// </summary>
        public static string SortDescription_Direction
        {
            get { return GetString("SortDescription_Direction"); }
        }

        /// <summary>
        /// {input} is required.
        /// </summary>
        public static string SortDescription_InputRequired(object input)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("SortDescription_InputRequired", "input"), input);
        }

        /// <summary>
        /// Delete Level
        /// </summary>
        public static string SortEditorWindow_DeleteLevel
        {
            get { return GetString("SortEditorWindow_DeleteLevel"); }
        }

        /// <summary>
        /// Sort
        /// </summary>
        public static string SortEditorWindow_Title
        {
            get { return GetString("SortEditorWindow_Title"); }
        }

        /// <summary>
        /// Cancel
        /// </summary>
        public static string _Cancel
        {
            get { return GetString("_Cancel"); }
        }

        /// <summary>
        /// OK
        /// </summary>
        public static string _OK
        {
            get { return GetString("_OK"); }
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
