// <auto-generated />
namespace DevZest.Data.AspNetCore
{
    using System.Diagnostics;
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class DiagnosticMessages
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("DevZest.Data.AspNetCore.DiagnosticMessages", typeof(DiagnosticMessages).GetTypeInfo().Assembly);

        /// <summary>
        /// DataRow is invalid for Column.
        /// </summary>
        public static string InvalidDataRowForColumn
        {
            get { return GetString("InvalidDataRowForColumn"); }
        }

        /// <summary>
        /// DataRow is invalid for DataSet.
        /// </summary>
        public static string InvalidDataRowForDataSet
        {
            get { return GetString("InvalidDataRowForDataSet"); }
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
