//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevZest.Data.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevZest.Data.Tools.UserMessages", typeof(UserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ButtonText_Back {
            get {
                return ResourceManager.GetString("ButtonText_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string ButtonText_Cancel {
            get {
                return ResourceManager.GetString("ButtonText_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonText_Close {
            get {
                return ResourceManager.GetString("ButtonText_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string ButtonText_OK {
            get {
                return ResourceManager.GetString("ButtonText_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Refresh.
        /// </summary>
        public static string ButtonText_Refresh {
            get {
                return ResourceManager.GetString("ButtonText_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Check Constraint.
        /// </summary>
        public static string CheckConstraintWindow_Title {
            get {
                return ResourceManager.GetString("CheckConstraintWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate.
        /// </summary>
        public static string ComputationWindow_Mode_Aggregate {
            get {
                return ResourceManager.GetString("ComputationWindow_Mode_Aggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherit.
        /// </summary>
        public static string ComputationWindow_Mode_Inherit {
            get {
                return ResourceManager.GetString("ComputationWindow_Mode_Inherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Computation.
        /// </summary>
        public static string ComputationWindow_Title {
            get {
                return ResourceManager.GetString("ComputationWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation is cancelled..
        /// </summary>
        public static string ConsoleWindow_OperationCancelled {
            get {
                return ResourceManager.GetString("ConsoleWindow_OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when running the operation:.
        /// </summary>
        public static string ConsoleWindow_OperationFaulted {
            get {
                return ResourceManager.GetString("ConsoleWindow_OperationFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Custom Validator.
        /// </summary>
        public static string CustomValidatorWindow_Title {
            get {
                return ResourceManager.GetString("CustomValidatorWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate DataSet(s).
        /// </summary>
        public static string DataSetGenWindow_Title {
            get {
                return ResourceManager.GetString("DataSetGenWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate database without any data..
        /// </summary>
        public static string DbGenWindow_Description {
            get {
                return ResourceManager.GetString("DbGenWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building project {0}....
        /// </summary>
        public static string DbInitProjectRunner_BuildingProject {
            get {
                return ResourceManager.GetString("DbInitProjectRunner_BuildingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building project {0} failed..
        /// </summary>
        public static string DbInitProjectRunner_BuildingProjectFailed {
            get {
                return ResourceManager.GetString("DbInitProjectRunner_BuildingProjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building project {0} completed successfully..
        /// </summary>
        public static string DbInitProjectRunner_BuildingProjectSucceeded {
            get {
                return ResourceManager.GetString("DbInitProjectRunner_BuildingProjectSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console App (.NET Core).
        /// </summary>
        public static string DbInitProjectRunner_ConsoleAppNetCore {
            get {
                return ResourceManager.GetString("DbInitProjectRunner_ConsoleAppNetCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console App (.NET Framework).
        /// </summary>
        public static string DbInitProjectRunner_ConsoleAppNetFramework {
            get {
                return ResourceManager.GetString("DbInitProjectRunner_ConsoleAppNetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed with exit code {0}..
        /// </summary>
        public static string DbInitProjectRunner_OperationFailed {
            get {
                return ResourceManager.GetString("DbInitProjectRunner_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully..
        /// </summary>
        public static string DbInitProjectRunner_OperationSucceeded {
            get {
                return ResourceManager.GetString("DbInitProjectRunner_OperationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project {0} is not supported. Supported project types are: {1}..
        /// </summary>
        public static string DbInitProjectRunner_ProjectNotSupported {
            get {
                return ResourceManager.GetString("DbInitProjectRunner_ProjectNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting process: {0} {1}.
        /// </summary>
        public static string DbInitProjectRunner_StartingProcess {
            get {
                return ResourceManager.GetString("DbInitProjectRunner_StartingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying project {0}....
        /// </summary>
        public static string DbInitProjectRunner_VerifyingProject {
            get {
                return ResourceManager.GetString("DbInitProjectRunner_VerifyingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add DbTable.
        /// </summary>
        public static string DbTableWindow_Title {
            get {
                return ResourceManager.GetString("DbTableWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db Visualizer.
        /// </summary>
        public static string DbVisualizer_Caption {
            get {
                return ResourceManager.GetString("DbVisualizer_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK Name:.
        /// </summary>
        public static string ForeignKeyWindow_Label_FkName {
            get {
                return ResourceManager.GetString("ForeignKeyWindow_Label_FkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK Type:.
        /// </summary>
        public static string ForeignKeyWindow_Label_FkType {
            get {
                return ResourceManager.GetString("ForeignKeyWindow_Label_FkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Foreign Key.
        /// </summary>
        public static string ForeignKeyWindow_Title {
            get {
                return ResourceManager.GetString("ForeignKeyWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string IndexWindow_CheckBox_Table {
            get {
                return ResourceManager.GetString("IndexWindow_CheckBox_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Table.
        /// </summary>
        public static string IndexWindow_CheckBox_TempTable {
            get {
                return ResourceManager.GetString("IndexWindow_CheckBox_TempTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique.
        /// </summary>
        public static string IndexWindow_CheckBox_Unique {
            get {
                return ResourceManager.GetString("IndexWindow_CheckBox_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Index.
        /// </summary>
        public static string IndexWindow_Title {
            get {
                return ResourceManager.GetString("IndexWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_bName:.
        /// </summary>
        public static string Label_DbName {
            get {
                return ResourceManager.GetString("Label_DbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteRule:.
        /// </summary>
        public static string Label_DeleteRule {
            get {
                return ResourceManager.GetString("Label_DeleteRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Description:.
        /// </summary>
        public static string Label_Description {
            get {
                return ResourceManager.GetString("Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Foreign Key:.
        /// </summary>
        public static string Label_ForeignKey {
            get {
                return ResourceManager.GetString("Label_ForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Mode:.
        /// </summary>
        public static string Label_Mode {
            get {
                return ResourceManager.GetString("Label_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Model:.
        /// </summary>
        public static string Label_Model {
            get {
                return ResourceManager.GetString("Label_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Referenced Table:.
        /// </summary>
        public static string Label_RefTable {
            get {
                return ResourceManager.GetString("Label_RefTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Db Log.
        /// </summary>
        public static string Label_ShowDbLog {
            get {
                return ResourceManager.GetString("Label_ShowDbLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Type Name:.
        /// </summary>
        public static string Label_TypeName {
            get {
                return ResourceManager.GetString("Label_TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateRule:.
        /// </summary>
        public static string Label_UpdateRule {
            get {
                return ResourceManager.GetString("Label_UpdateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDO.Tools License.
        /// </summary>
        public static string LicenseWindow_Title {
            get {
                return ResourceManager.GetString("LicenseWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        public static string MessageView_Label {
            get {
                return ResourceManager.GetString("MessageView_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Missing MessageResource attribute).
        /// </summary>
        public static string MessageView_MissingMessageResourceAttribute {
            get {
                return ResourceManager.GetString("MessageView_MissingMessageResourceAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required..
        /// </summary>
        public static string MessageView_ValueIsRequired {
            get {
                return ResourceManager.GetString("MessageView_ValueIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model &apos;{0}&apos;.
        /// </summary>
        public static string ModelPresenter_ModelNameFormat {
            get {
                return ResourceManager.GetString("ModelPresenter_ModelNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Key.
        /// </summary>
        public static string ModelVisualizer_AddKey {
            get {
                return ResourceManager.GetString("ModelVisualizer_AddKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Ref.
        /// </summary>
        public static string ModelVisualizer_AddRef {
            get {
                return ResourceManager.GetString("ModelVisualizer_AddRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Visualizer.
        /// </summary>
        public static string ModelVisualizer_Caption {
            get {
                return ResourceManager.GetString("ModelVisualizer_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Key:.
        /// </summary>
        public static string PrimaryKeyWindow_Label_Key {
            get {
                return ResourceManager.GetString("PrimaryKeyWindow_Label_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ref:.
        /// </summary>
        public static string PrimaryKeyWindow_Label_Ref {
            get {
                return ResourceManager.GetString("PrimaryKeyWindow_Label_Ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Primary Key.
        /// </summary>
        public static string PrimaryKeyWindow_Title {
            get {
                return ResourceManager.GetString("PrimaryKeyWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By Selection.
        /// </summary>
        public static string ProjectionWindow_SortBySelection {
            get {
                return ResourceManager.GetString("ProjectionWindow_SortBySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Projection.
        /// </summary>
        public static string ProjectionWindow_Title {
            get {
                return ResourceManager.GetString("ProjectionWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Relationship.
        /// </summary>
        public static string RelationshipWindow_Title {
            get {
                return ResourceManager.GetString("RelationshipWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string SortDirection_Asc {
            get {
                return ResourceManager.GetString("SortDirection_Asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string SortDirection_Desc {
            get {
                return ResourceManager.GetString("SortDirection_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Title_DbInitInput {
            get {
                return ResourceManager.GetString("Title_DbInitInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Db.
        /// </summary>
        public static string Title_GenerateDb {
            get {
                return ResourceManager.GetString("Title_GenerateDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Unique Constraint.
        /// </summary>
        public static string UniqueConstraintWindow_Title {
            get {
                return ResourceManager.GetString("UniqueConstraintWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required.
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
    }
}
