//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevZest.Data.CodeAnalysis {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevZest.Data.CodeAnalysis.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; passed to CandidateKey constructor does not match the parameter name &apos;{1}&apos;..
        /// </summary>
        internal static string CandidateKeyArgumentNaming_Message {
            get {
                return ResourceManager.GetString("CandidateKeyArgumentNaming_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CandidateKey argument naming rule violation..
        /// </summary>
        internal static string CandidateKeyArgumentNaming_Title {
            get {
                return ResourceManager.GetString("CandidateKeyArgumentNaming_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument passed to CandidateKey constructor must be a column of current Model..
        /// </summary>
        internal static string CandidateKeyInvalidArgument_Message {
            get {
                return ResourceManager.GetString("CandidateKeyInvalidArgument_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CandidateKey argument..
        /// </summary>
        internal static string CandidateKeyInvalidArgument_Title {
            get {
                return ResourceManager.GetString("CandidateKeyInvalidArgument_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CandidateKey constructor parameter &apos;{0}&apos; must be Column..
        /// </summary>
        internal static string CandidateKeyInvalidConstructorParam_Message {
            get {
                return ResourceManager.GetString("CandidateKeyInvalidConstructorParam_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CandidateKey constructor parameter..
        /// </summary>
        internal static string CandidateKeyInvalidConstructorParam_Title {
            get {
                return ResourceManager.GetString("CandidateKeyInvalidConstructorParam_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CandidateKey must have one constructor only..
        /// </summary>
        internal static string CandidateKeyInvalidConstructors_Message {
            get {
                return ResourceManager.GetString("CandidateKeyInvalidConstructors_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CondidateKey constructors..
        /// </summary>
        internal static string CandidateKeyInvalidConstructors_Title {
            get {
                return ResourceManager.GetString("CandidateKeyInvalidConstructors_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatch in number of arguments passed to CandidateKey base constructor, {0} argument(s) expected..
        /// </summary>
        internal static string CandidateKeyMismatchBaseConstructor_Message {
            get {
                return ResourceManager.GetString("CandidateKeyMismatchBaseConstructor_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatch in number of arguments passed to CandidateKey base constructor..
        /// </summary>
        internal static string CandidateKeyMismatchBaseConstructor_Title {
            get {
                return ResourceManager.GetString("CandidateKeyMismatchBaseConstructor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument mismatch in CandidateKey base constructor, {0}, {0}.Asc() or {0}.Desc() expected..
        /// </summary>
        internal static string CandidateKeyMismatchBaseConstructorArgument_Message {
            get {
                return ResourceManager.GetString("CandidateKeyMismatchBaseConstructorArgument_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument mismatch in CandidateKey base constructor..
        /// </summary>
        internal static string CandidateKeyMismatchBaseConstructorArgument_Title {
            get {
                return ResourceManager.GetString("CandidateKeyMismatchBaseConstructorArgument_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CandidateKey SortAttribute mismatch: constructor - {0}, base - {1}..
        /// </summary>
        internal static string CandidateKeyMismatchSortAttribute_Message {
            get {
                return ResourceManager.GetString("CandidateKeyMismatchSortAttribute_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CandidateKey SortAttribute mismatch..
        /// </summary>
        internal static string CandidateKeyMismatchSortAttribute_Title {
            get {
                return ResourceManager.GetString("CandidateKeyMismatchSortAttribute_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invocation to CandidateKey base constructor is missing..
        /// </summary>
        internal static string CandidateKeyMissingBaseConstructor_Message {
            get {
                return ResourceManager.GetString("CandidateKeyMissingBaseConstructor_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing CandidateKey base initializer..
        /// </summary>
        internal static string CandidateKeyMissingBaseConstructor_Title {
            get {
                return ResourceManager.GetString("CandidateKeyMissingBaseConstructor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class derived from CondidateKey should be sealed..
        /// </summary>
        internal static string CandidateKeyNotSealed_Message {
            get {
                return ResourceManager.GetString("CandidateKeyNotSealed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CandidateKey should be sealed..
        /// </summary>
        internal static string CandidateKeyNotSealed_Title {
            get {
                return ResourceManager.GetString("CandidateKeyNotSealed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameterless constructor is not valid for CandidateKey..
        /// </summary>
        internal static string CandidateKeyParameterlessConstructor_Message {
            get {
                return ResourceManager.GetString("CandidateKeyParameterlessConstructor_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameterless CandidateKey constructor..
        /// </summary>
        internal static string CandidateKeyParameterlessConstructor_Title {
            get {
                return ResourceManager.GetString("CandidateKeyParameterlessConstructor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asc and Desc attributes are mutually exclusive..
        /// </summary>
        internal static string CandidateKeySortAttributeConflict_Message {
            get {
                return ResourceManager.GetString("CandidateKeySortAttributeConflict_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CandidateKey SortAttribute conflict..
        /// </summary>
        internal static string CandidateKeySortAttributeConflict_Title {
            get {
                return ResourceManager.GetString("CandidateKeySortAttributeConflict_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate declaration attribute {0} with name {1}..
        /// </summary>
        internal static string DuplicateDeclarationAttribute_Message {
            get {
                return ResourceManager.GetString("DuplicateDeclarationAttribute_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate declaration attribute..
        /// </summary>
        internal static string DuplicateDeclarationAttribute_Title {
            get {
                return ResourceManager.GetString("DuplicateDeclarationAttribute_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate registration for property &apos;{0}&apos;..
        /// </summary>
        internal static string DuplicateRegistration_Message {
            get {
                return ResourceManager.GetString("DuplicateRegistration_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate property registration..
        /// </summary>
        internal static string DuplicateRegistration_Title {
            get {
                return ResourceManager.GetString("DuplicateRegistration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute {0} should be applied for {1} that returns {2}, with parameters ({3})..
        /// </summary>
        internal static string InvalidImplementationAttribute_Message {
            get {
                return ResourceManager.GetString("InvalidImplementationAttribute_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid implementation attribute..
        /// </summary>
        internal static string InvalidImplementationAttribute_Title {
            get {
                return ResourceManager.GetString("InvalidImplementationAttribute_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local column &apos;{0}&apos; is invalid for RegisterColumn, use RegisterLocalColumn instead..
        /// </summary>
        internal static string InvalidLocalColumnRegistration_Message {
            get {
                return ResourceManager.GetString("InvalidLocalColumnRegistration_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local column is invalid for RegisterColumn..
        /// </summary>
        internal static string InvalidLocalColumnRegistration_Title {
            get {
                return ResourceManager.GetString("InvalidLocalColumnRegistration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The getter parameter must be a lambda expression which returns a non-readonly property of current class..
        /// </summary>
        internal static string InvalidRegistrationGetterParam_Message {
            get {
                return ResourceManager.GetString("InvalidRegistrationGetterParam_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid getter of property registration..
        /// </summary>
        internal static string InvalidRegistrationGetterParam_Title {
            get {
                return ResourceManager.GetString("InvalidRegistrationGetterParam_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property registration is only allowed as static field initializer or static constructor statement..
        /// </summary>
        internal static string InvalidRegistrationInvocation_Message {
            get {
                return ResourceManager.GetString("InvalidRegistrationInvocation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid invocation of property registration..
        /// </summary>
        internal static string InvalidRegistrationInvocation_Title {
            get {
                return ResourceManager.GetString("InvalidRegistrationInvocation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing declaration attribute {0} with name {1}..
        /// </summary>
        internal static string MissingDeclarationAttribute_Message {
            get {
                return ResourceManager.GetString("MissingDeclarationAttribute_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing declaration attribute..
        /// </summary>
        internal static string MissingDeclarationAttribute_Title {
            get {
                return ResourceManager.GetString("MissingDeclarationAttribute_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing implementation of instance {0} {1}, which returns {2}, with parameters ({3})..
        /// </summary>
        internal static string MissingImplementation_Message {
            get {
                return ResourceManager.GetString("MissingImplementation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing implementation..
        /// </summary>
        internal static string MissingImplementation_Title {
            get {
                return ResourceManager.GetString("MissingImplementation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing implementation attribute: {0}..
        /// </summary>
        internal static string MissingImplementationAttribute_Message {
            get {
                return ResourceManager.GetString("MissingImplementationAttribute_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing implementation attribute..
        /// </summary>
        internal static string MissingImplementationAttribute_Title {
            get {
                return ResourceManager.GetString("MissingImplementationAttribute_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing registration for property &apos;{0}&apos;..
        /// </summary>
        internal static string MissingRegistration_Message {
            get {
                return ResourceManager.GetString("MissingRegistration_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing property registration..
        /// </summary>
        internal static string MissingRegistration_Title {
            get {
                return ResourceManager.GetString("MissingRegistration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute {0} is valid on type {1}, while applied model member is type {2}..
        /// </summary>
        internal static string ModelDesignerSpecInvalidType_Message {
            get {
                return ResourceManager.GetString("ModelDesignerSpecInvalidType_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid model member attribute..
        /// </summary>
        internal static string ModelDesignerSpecInvalidType_Title {
            get {
                return ResourceManager.GetString("ModelDesignerSpecInvalidType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute {0} requires argument..
        /// </summary>
        internal static string ModelDesignerSpecRequiresArgument_Message {
            get {
                return ResourceManager.GetString("ModelDesignerSpecRequiresArgument_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model member attribute requires argument..
        /// </summary>
        internal static string ModelDesignerSpecRequiresArgument_Title {
            get {
                return ResourceManager.GetString("ModelDesignerSpecRequiresArgument_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounter &apos;{0}&apos; of property &apos;{1}&apos; does not conform to naming convention, rename to &apos;{2}&apos;..
        /// </summary>
        internal static string MounterNaming_Message {
            get {
                return ResourceManager.GetString("MounterNaming_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounter naming convention violation..
        /// </summary>
        internal static string MounterNaming_Title {
            get {
                return ResourceManager.GetString("MounterNaming_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection column &apos;{0}&apos; from Mounter &apos;{1}&apos; violates naming convention..
        /// </summary>
        internal static string ProjectionColumnNaming_Message {
            get {
                return ResourceManager.GetString("ProjectionColumnNaming_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection column naming convention violation..
        /// </summary>
        internal static string ProjectionColumnNaming_Title {
            get {
                return ResourceManager.GetString("ProjectionColumnNaming_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to method.
        /// </summary>
        internal static string StringFormatArg_Method {
            get {
                return ResourceManager.GetString("StringFormatArg_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to property.
        /// </summary>
        internal static string StringFormatArg_Property {
            get {
                return ResourceManager.GetString("StringFormatArg_Property", resourceCulture);
            }
        }
    }
}
