//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevZest.Data.CodeAnalysis {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevZest.Data.CodeAnalysis.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate mounter registration for property &apos;{0}&apos;..
        /// </summary>
        internal static string DuplicateMounterRegistration_Message {
            get {
                return ResourceManager.GetString("DuplicateMounterRegistration_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate mounter registration..
        /// </summary>
        internal static string DuplicateMounterRegistration_Title {
            get {
                return ResourceManager.GetString("DuplicateMounterRegistration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local column &apos;{0}&apos; is invalid for RegisterColumn, use RegisterLocalColumn instead..
        /// </summary>
        internal static string InvalidRegisterLocalColumn_Message {
            get {
                return ResourceManager.GetString("InvalidRegisterLocalColumn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local column is invalid for RegisterColumn..
        /// </summary>
        internal static string InvalidRegisterLocalColumn_Title {
            get {
                return ResourceManager.GetString("InvalidRegisterLocalColumn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The getter parameter must be a lambda expression which returns a non-readonly property of current class..
        /// </summary>
        internal static string InvalidRegisterMounterGetterParam_Message {
            get {
                return ResourceManager.GetString("InvalidRegisterMounterGetterParam_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid getter of mounter registration..
        /// </summary>
        internal static string InvalidRegisterMounterGetterParam_Title {
            get {
                return ResourceManager.GetString("InvalidRegisterMounterGetterParam_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounter registration is only allowed as static field initializer or static constructor statement..
        /// </summary>
        internal static string InvalidRegisterMounterInvocation_Message {
            get {
                return ResourceManager.GetString("InvalidRegisterMounterInvocation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid invocation of mounter registration..
        /// </summary>
        internal static string InvalidRegisterMounterInvocation_Title {
            get {
                return ResourceManager.GetString("InvalidRegisterMounterInvocation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing registration for model property &apos;{0}&apos;..
        /// </summary>
        internal static string MissingMounterRegistration_Message {
            get {
                return ResourceManager.GetString("MissingMounterRegistration_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing registration for model property..
        /// </summary>
        internal static string MissingMounterRegistration_Title {
            get {
                return ResourceManager.GetString("MissingMounterRegistration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounter &apos;{0}&apos; of property &apos;{1}&apos; does not conform to naming convention, rename mounter name &apos;{0}&apos; to &apos;{2}&apos;..
        /// </summary>
        internal static string MounterNaming_Message {
            get {
                return ResourceManager.GetString("MounterNaming_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounter naming rule violation..
        /// </summary>
        internal static string MounterNaming_Title {
            get {
                return ResourceManager.GetString("MounterNaming_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PrimaryKey constructor parameter &apos;{0}&apos; must be Column..
        /// </summary>
        internal static string PrimaryKeyInvalidConstructorParam_Message {
            get {
                return ResourceManager.GetString("PrimaryKeyInvalidConstructorParam_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PrimaryKey constructor parameter..
        /// </summary>
        internal static string PrimaryKeyInvalidConstructorParam_Title {
            get {
                return ResourceManager.GetString("PrimaryKeyInvalidConstructorParam_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimaryKey must have one constructor only..
        /// </summary>
        internal static string PrimaryKeyInvalidConstructors_Message {
            get {
                return ResourceManager.GetString("PrimaryKeyInvalidConstructors_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PrimaryKey constructors..
        /// </summary>
        internal static string PrimaryKeyInvalidConstructors_Title {
            get {
                return ResourceManager.GetString("PrimaryKeyInvalidConstructors_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatch in number of arguments passed to PrimaryKey base constructor, {0} argument(s) expected..
        /// </summary>
        internal static string PrimaryKeyMismatchBaseConstructor_Message {
            get {
                return ResourceManager.GetString("PrimaryKeyMismatchBaseConstructor_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatch in number of arguments passed to PrimaryKey base constructor..
        /// </summary>
        internal static string PrimaryKeyMismatchBaseConstructor_Title {
            get {
                return ResourceManager.GetString("PrimaryKeyMismatchBaseConstructor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument mismatch in PrimaryKey base constructor, {0}, {0}.Asc() or {0}.Desc() expected..
        /// </summary>
        internal static string PrimaryKeyMismatchBaseConstructorArgument_Message {
            get {
                return ResourceManager.GetString("PrimaryKeyMismatchBaseConstructorArgument_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument mismatch in PrimaryKey base constructor..
        /// </summary>
        internal static string PrimaryKeyMismatchBaseConstructorArgument_Title {
            get {
                return ResourceManager.GetString("PrimaryKeyMismatchBaseConstructorArgument_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimaryKey SortAttribute mismatch: constructor - {0}, base - {1}..
        /// </summary>
        internal static string PrimaryKeyMismatchSortAttribute_Message {
            get {
                return ResourceManager.GetString("PrimaryKeyMismatchSortAttribute_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimaryKey SortAttribute mismatch..
        /// </summary>
        internal static string PrimaryKeyMismatchSortAttribute_Title {
            get {
                return ResourceManager.GetString("PrimaryKeyMismatchSortAttribute_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invocation to PrimaryKey base constructor is missing..
        /// </summary>
        internal static string PrimaryKeyMissingBaseConstructor_Message {
            get {
                return ResourceManager.GetString("PrimaryKeyMissingBaseConstructor_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing PrimaryKey base initializer..
        /// </summary>
        internal static string PrimaryKeyMissingBaseConstructor_Title {
            get {
                return ResourceManager.GetString("PrimaryKeyMissingBaseConstructor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class derived from PrimaryKey should be sealed..
        /// </summary>
        internal static string PrimaryKeyNotSealed_Message {
            get {
                return ResourceManager.GetString("PrimaryKeyNotSealed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimaryKey should be sealed..
        /// </summary>
        internal static string PrimaryKeyNotSealed_Title {
            get {
                return ResourceManager.GetString("PrimaryKeyNotSealed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameterless constructor is not valid for PrimaryKey..
        /// </summary>
        internal static string PrimaryKeyParameterlessConstructor_Message {
            get {
                return ResourceManager.GetString("PrimaryKeyParameterlessConstructor_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameterless PrimaryKey constructor..
        /// </summary>
        internal static string PrimaryKeyParameterlessConstructor_Title {
            get {
                return ResourceManager.GetString("PrimaryKeyParameterlessConstructor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asc and Desc attributes are mutually exclusive..
        /// </summary>
        internal static string PrimaryKeySortAttributeConflict_Message {
            get {
                return ResourceManager.GetString("PrimaryKeySortAttributeConflict_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimaryKey SortAttribute conflict..
        /// </summary>
        internal static string PrimaryKeySortAttributeConflict_Title {
            get {
                return ResourceManager.GetString("PrimaryKeySortAttributeConflict_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection column &apos;{0}&apos; from existing Mounter &apos;{1}&apos; violates naming rule..
        /// </summary>
        internal static string ProjectionColumnNaming_Message {
            get {
                return ResourceManager.GetString("ProjectionColumnNaming_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection column naming rule violation..
        /// </summary>
        internal static string ProjectionColumnNaming_Title {
            get {
                return ResourceManager.GetString("ProjectionColumnNaming_Title", resourceCulture);
            }
        }
    }
}
